camp_name: "ML4good Singapore 2025"

# Google Drive folder ID where form shortcuts will be created
# To get the folder ID: open the folder in Google Drive and copy the ID from the URL
# Example: https://drive.google.com/drive/folders/1ABC123... → folder ID is "1ABC123..."
drive_folder_id: "1L-5O6adlMY8AFzFlEA3d7QA09ie7epDi"  # Leave empty to skip creating shortcuts

# Automatically copy folder permissions to the form
# When enabled, the form will inherit all access permissions from the specified Drive folder
# This ensures that anyone with access to the folder can also access the form
inherit_folder_permissions: false  # Set to false to keep default form permissions

teachers:
  - "Julian"
  - "Jonathan C"
  - "Jonathan N"
  - "Valerie"

form_description: |
  The goal of this form is to allow us to improve ML4Good day by day during the camp, and for the next participants. Thank you for all answers and extra comments.

  More detailed feedback is what helps us the most improve the workshops, both for the other days and the future iterations of the camp. All of it optional, but every bit of information will make someone's life better (yours or future/other participants).

  You can add many bullet points, each of them will help us to gradient descent in the right direction. Examples:
  Not enough talks/guidance
  Too fast
  Instructions unclear
  I'm confused about the material
  I learned a lot
  There was too many details
  (feel free to just copy paste the bullet points that apply!)

pre_questions:
  - text: "Name"
    kind: "text"
    mandatory: true
  
  - text: "What was your highlight of the day?"
    kind: "paragraph"
    mandatory: false
  
  - text: "What do you think about the amount of content we had today?"
    kind: "scale_5_point"
    scale_left: "too little"
    scale_right: "too much"
    mandatory: false

timetable:
  day_1:
    meme: "balloon.png"
    sessions:
      - name: "Intro talk (yesterday evening)"
      - name: "Icebreaker + Quiz"
      - name: "Optimizers & Hyperparameters (lecture)"
      - name: "Optimizers & Hyperparameters (exercise)"
      - name: "Chapter 1 Capabilities"
        reading_group: true
      - name: "Agents (lecture)"
      - name: "Agents (exercise)"
      - name: "How to create an AGI?"
      - name: "Evals (lecture)"
      - name: "Evals (exercise)"
    day_questions:
      - text: "Riddle of the day: Derive the Adam bias correction term"
        kind: "paragraph"
        mandatory: false
 
  
  day_2:
    meme: "drake.png"
    sessions:
      - name: "Transformers"
      - name: "Evals (lecture)"
      - name: "Evals (exercise)"
      - name: "AI Control lecture"
      - name: "TA inspiration"
      - name: "Red teaming"
    day_questions:
      - text: "How would you rate the food today?"
        kind: "scale_5_point"
        scale_left: "poor"
        scale_right: "excellent"
        mandatory: false
      - text: "Comments on the food today"
        kind: "paragraph"
        mandatory: false
      - text: "Where you ok with the knowledge quiz?"
        kind: "paragraph"
        mandatory: false

  day_3:
    meme: "flipchart.png"
    sessions:
 
      - name: "Transformer Interpretability"
      - name: "Chapter 3 - Solutions"
        reading_group: true
      - name: "Workshop: Timelines"
      - name: "Cursor/Discussion/Controle Q&A"
        reading_group: true
      - name: "One on ones"
  day_4:
    meme: "brain.png"
    sessions:
      - name: "Chapter 4: Governance"
        reading_group: true
      - name: "AI Safety bills lecture"
      - name: "Safety cases lecture"
      - name: "Tekla Emborg - Future of Life Institute"
      - name: "Literature Review"
 

  day_5:
    meme: "buttons.png"
    sessions:
      - name: "RLHF (lecture)"
      - name: "Reasoning Models (lecture)"
      - name: "CoT Faithfulness (exercise)"
      - name: "Scalable oversight"
        reading_group: true
      - name: "One on Ones"
      - name: "Theory of change workshop"
      - name: "Career Planning"
      - name: "Project brainstorm"
 

  day_6:
    meme: "swerfe.png"
    sessions:
      - name: "Guest Talk: Jan Kirchner (yesterday)"
      - name: "Project red teaming"
      - name: "Project Work"
      - name: "Career meetings (only fill out if you had yours today)"
 

  day_7:
    meme: "swerfe.png"
    sessions:
      - name: "Project Work"
      - name: "Career meetings"
      - name: "Jan Kirchner - Anthropic"
      - name: "Edward Young - Geodesic Research"
      - name: "Everyone present some results"
      - name: "Career plan"
      - name: "Heuristics, resources and next steps"
      - name: "Closing session"
      - name: "Party 🎉"

post_questions:
  - text: "Overall Experience: How would you rate your overall experience of the past 24 hours?"
    kind: "scale_1_10"
    mandatory: true
  
  - text: "How are your energy levels?"
    kind: "scale_1_10"
    mandatory: true
  
  - text: "What did you learn today, that you definitely want to remember?"
    kind: "text"
    mandatory: false
  
  - text: "Open comments"
    kind: "text"
    mandatory: false 